### ISSUE TITLE
Pathfinding with respect to 'occupied' nodes

### ISSUE THREAD

**Issue by Jacquies** [Yoshgunn/LightShadowThrowaway#15]
As of now, the way the pathfinding works is that nodes can be 'disabled', so they won't be used at all for any pathfinding calculations.

They can also be 'occupied'. 'Occupied' nodes are treated just like normal nodes and are used for pathfinding in the same way. The only difference is that, when an entity (player/walker) attempts to move into an 'occupied' node, it will stop and wait for the node to become 'unoccupied'.

This behavior exhibits what we are looking for, for the most part. However, there may be cases where the player is in the path of a walker (so the walker will wait for the player to move). The player is simultaneously attempting to move to another space. The pathfinding algorithm may have chosen the space occupied by the walker (even if there is another option), so both entities are waiting on each other.

**Comment by Jacquies** [comment]
Actually, I think I fixed this (by applying a higher cost to occupied nodes while pathfinding). For longer paths, this may not fix the problem (if the node becomes 'occupied' while the player is moving), but it will work in most situations.

I will leave this issue open due to the outstanding issue above (it really is exceptional, isn't it?), as well as the complexity of the issue, which means that the fix might not be sufficient.

**Comment by Yoshgunn** [comment]
Was this why crows started "cawing" at you in Monument Valley when you blocked their path? Maybe it was feedback related to their state changing from moving to "being stuck." I guess you could do something where if their path is blocked, their target destination becomes the space they are currently on, and they get really pissed off? _shrug_

**Comment by Jacquies** [comment]
Yeah, I was trying to emulate the way the crows worked when I had them 'waiting' for you to move. It would be pretty easy to put in something that happens when they're waiting that would be similar to the 'cawing'.

Since walkers have slightly more complex interactions with the player than other mechanics, at our next meeting we should discuss exactly how they interact with the player, both in terms of mechanical behavior (do they wait, or just turn around?) and aesthetic behavior (do they do anything to show they are 'mad' or something?).

**Comment by Jacquies** [comment]
Pathfinding will now take into account which nodes are occupied. Additionally, when the player is waiting for a node to become unoccupied for over 1 second (the time can be easily changed), he will try to find a new path. We can also apply this logic to Walkers if we decide to.
