### ISSUE TITLE
'Constant Light' and Animations

### ISSUE THREAD

**Issue by Jacquies** [Yoshgunn/LightShadowThrowaway#30]
There's something very wrong with this project right now - two of our major assets aren't able to play nice together or something.

Check out the protagonist level. I changed some of the materials, so that it's using the same materials as the rest of the levels. However, the 'constant light' effect we managed to use for the other levels doesn't seem to apply in this level, even though the settings are the same. Similarly, I can't seem to import the 'pretty player' into any levels other than the one he is already in. Since I know you can use him in other levels, maybe you should see if you see the expected light behavior in the protagonist scene now. Hopefully it's just an issue with the way we're trying to send art assets and settings around or something.

**Comment by Yoshgunn** [comment]
Uh oh! I'll check it out tomorrow, if not tonight. That sucks. I can definitely look into what's going on with the protagonist being imported. But what's this about a constant light effect? What do you mean by that exactly? (Screenshot?) Is this the changes you made to the attenuation in the shader?

**Comment by Jacquies** [comment]
Yeah, I couldn't think of how to phrase it. It's the shader attenuation
change, with the crisper edges to the light.

**Comment by Yoshgunn** [comment]
I still haven't gotten a chance to check it out yet but if I had to guess I'd say this - the floor has a material on it called FlatShade. I made it (I think?) and I put it on all the floors because I felt they were too glossy. Unless you switched that over to the correct shader, it's likely still using the Standard Shader, which is going to cause an issue.

It looks really similar to the other grey shader which is probably why it went unnoticed, if I'm right. Whoops!

**Comment by Jacquies** [comment]
I thought I had changed the flat shade one to the correct shader,unless you
updated it recently. I guess you can take a look and see. I also tried it
with a different material with the correct shader (I thought).

Let me know if you notice anything amiss.

**Comment by Yoshgunn** [comment]
# Lighting

Well this is weird! I'm getting the same bad light behavior. The ground is pixelated! (Love the lantern flickering, btw) 

![image](https://cloud.githubusercontent.com/assets/4043081/9308805/179d8322-44d4-11e5-94ed-30e5248ff3aa.png)
(Game View)

Now here's the punchline. The second picture is the same exact scene but in the Scene view! WTF? The scene looks different from the game! Notice how it is all smooth and nice. Something weird is going on here...

![image](https://cloud.githubusercontent.com/assets/4043081/9308838/3dd1c454-44d4-11e5-99d7-be2fe59c655a.png)
(Scene View)

# Protagonist

I was able to import the PrettyPlayer Prefab into our Wandering Monolith level. I dragged it in and set it up in the place you put the normal player. Then I hid the normal player (disabled the GameObject, rather) and the PrettyPlayer seems to be working OK. The lighting doesn't quite seem to be the way you set it up, but the level is small so it's hard to tell... is this the behavior you expected?

![image](https://cloud.githubusercontent.com/assets/4043081/9308992/0c17f5a4-44d5-11e5-8e9c-058823ad17e6.png)

**Comment by Yoshgunn** [comment]
I'll try changing the Blender materials?!

**Comment by Jacquies** [comment]
I figured out the lighting bug! Unfortunately, while it's easy to fix, the fix is actually something we don't want to do.

When I was creating new levels and the lighting was working, I was just using the default camera, which is using a perspective projection. When you change it to an orthographic projection, it causes the strange lighting behavior we've been seeing (which is why the Scene view always looks good - it uses a perspective projection by default).

So it seems that something in the rendering pipeline with an orthographic projection camera causes this strange light behavior. Unless we can figure out another way to create the lighting attenuation we've been looking for, we might be stuck with a perspective projection.

Honestly, that might not be the worst thing. I know it's a little worse for performance, but I don't think that the orthographic projection was absolutely necessary. What do you think?

**Comment by Yoshgunn** [comment]
Hmm we'll lose a bit of the Momument Valley aesthetic if we do. Maybe we
should use Perspective but lower the field of view to near-orthohraphic
levels.

I think it's worth investigating why this occurs. Maybe we need to edit the
Light script OR make some edits to the camera?

**Comment by Jacquies** [comment]
So I was making the stress test level, and it became pretty obvious that having the orthographic perspective is important, so I think we should see if we can figure out a way to use it.

I did some Googling, and it looks like the orthographic perspective can't be used with deferred rendering, and will default to forward rendering. However, the shader changes we made only work for deferred rendering. That's why we're seeing the problem.

I think there's a way to change the light attenuation for forward rendering, but it might be complicated. I'll keep looking into it and see what I can do.

**Comment by Jacquies** [comment]
Well, I figured out how to get the attenuation we were looking for with forward rendering, so we can use it with the orthographic projection! Check it out:

![orthographic attenuation](https://cloud.githubusercontent.com/assets/168099/9621190/7919538c-50f1-11e5-8c89-b7a269769ea1.PNG)

**Comment by Yoshgunn** [comment]
OMG DUDE THAT LOOKS SO GOOD!!

How did you figure it out? From what I understood, the shadows were too "far away" to display correctly through an orthographic projection. Is that what it was?

P.S. Sick level btw! I like the canopy thingies

**Comment by Yoshgunn** [comment]
By the way, should this Issue be closed now, or is there still a problem?

**Comment by Jacquies** [comment]
I think I had just left it open so that if there was anything you wanted to point out about it, we could still work on it. I think that we have successfully addresses the issue discussed here, so I'll go ahead and close it.
