### ISSUE TITLE
Monoliths State Rotation

### ISSUE THREAD

**Issue by Jacquies** [Yoshgunn/LightShadowThrowaway#34]
Right now, (most) monoliths can have any number of states, and when they change, they simply move to the next state. This is exactly what we want.

However, I think right now, they will always _loop_, so if you get to the last one, it will then go to the first one.

I would like to add (to all monoliths with more than two states) the ability to either loop or reverse (so that once you get to the last one, you then run through the list again backwards until you get to the first).

**Comment by Yoshgunn** [comment]
That's a good idea. I can think of a few puzzles already that could utilize this.

Think we'll have any need for a Monolith that stops? (that is, it doesn't loop or reverse, it just stays in it's final form forever)

**Comment by Jacquies** [comment]
That's a good point. I'll make sure to add functionality for looping as well as stopping.

**Comment by Jacquies** [comment]
Updated monolith state rotation - they can now loop or 'bounce' back and forth. You can also specify that they should stop once they reach the end.

This update was not made to portal monoliths - I updated them in a way that more accurately shows how I think they should work. It's hard to explain, so you should take a look.

Basically, if you're looking at the portal monolith from one position (between two pillars, say), then it should always try to be the same from that position, so that it really matters what direction you're passing the pillar.
